### ISSUE TITLE
Incomplete implementation, leads to many downstream bugs

### ISSUE THREAD

**Issue by StephanPreibisch** [bigdataviewer/spimdata#11]
Hi @tpietzsch,

this line fails: https://github.com/bigdataviewer/spimdata/blob/9dbb4b3d0bf677c7f1981df3cfb6b34ac6672657/src/main/java/mpicbg/spim/data/generic/sequence/XmlIoBasicImgLoader.java#L74

if the URI file path does not start with "file:/", which is the normal case in the legacy code, the path will be e.g. "/home/data.xml" and not "file:/home/data.xml" ... My solution is this:

https://github.com/PreibischLab/multiview-reconstruction/blob/b102f2e3092f620a6e23f80061b547d362200548/src/main/java/util/URITools.java#L497-L506

Let's chat how to move forward, for now I implement it like that in my XMLIO's ... https://github.com/PreibischLab/multiview-reconstruction/commit/38f164527d2f23780599480248473e49271681e7

Alternatively, we could also always add "file:/" if it is missing ...

**Comment by tpietzsch** [comment]
From your explanation, I don't understand what the problem is? What is "the URI file path"? `basePathURI`? and if that does not start with "file:/" it fails in what way?

**Comment by tpietzsch** [comment]
Ok, I think I understand now.
The problem is actually in https://github.com/bigdataviewer/spimdata/blob/ec9eaa18c3698465e48ed43b42eb8255c422932f/src/main/java/mpicbg/spim/data/XmlHelpers.java#L287-L310
in particular
https://github.com/bigdataviewer/spimdata/blob/ec9eaa18c3698465e48ed43b42eb8255c422932f/src/main/java/mpicbg/spim/data/XmlHelpers.java#L303
This should add the "file:/" prefix for absolute paths (if no prefix is given). Otherwise, it will construct a URI (but a relative URI, without a scheme). And that's wrong.
In the location that you pointed out, everything is ok like it is. We can expect that the `basePathURI` is absolute, with scheme and all.

**Comment by StephanPreibisch** [comment]
we also need to consider older XML's that do not start with a scheme ...

**Comment by StephanPreibisch** [comment]
we'll figure the best way out tomorrow ...

**Comment by tpietzsch** [comment]
This should be fixed in `spim_data-2.3.5`
Regarding the no-longer-saves-relative-basePath issue:
I tried it, and the `XmlIoAbstractSpimData` does it correctly, ultimately here:
https://github.com/bigdataviewer/spimdata/blob/946d880a9250c495f73aa1d0374e1dbc38b842fe/src/main/java/mpicbg/spim/data/XmlHelpers.java#L439-L443
If the SpimData basePath can be made relative to the path where the XML is stored, it is stored as "relative".

I think the issue must be in multiview-reconstruction somewhere.
The `XmlHelpers. pathElementURI` method, where the relativizing happens now throws `IllegalArgumentException` if any of the involved URIs is not absolute.
https://github.com/bigdataviewer/spimdata/blob/946d880a9250c495f73aa1d0374e1dbc38b842fe/src/main/java/mpicbg/spim/data/XmlHelpers.java#L423-L429
Maybe that helps debugging the issue?
